engines:
  rubocop:
    enabled: true
  golint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  phpcodesniffer:
    enabled: true
ratings:
  paths:
  - src/**
  - app/**
  - web/**

exclude_paths:
- "tests/"
- "spec/"
- "**/vendor/"
- "var/"
- "bin/"
