language: php
sudo: required
addons:
  apt:
    packages:
    - ldap-utils
    - slapd
before_script:
  - echo "Before Script"
  - sudo service slapd stop
  - sleep 3
  - sudo rm /etc/ldap/slapd.d/* -R
  - sudo rm /var/lib/ldap/* -R
  - sudo cp ./pbnl/pbnl-ldap-gui/ldap-test-files/slapd.d/* /etc/ldap/slapd.d/
  - sudo cp ./pbnl/pbnl-ldap-gui/ldap-test-files/ldap/* /var/lib/ldap/
  - sudo service slapd start
  
