language: php
sudo: required
addons:
  apt:
    packages:
    - ldap-utils
    - slapd
    - php5-ldap
before_script:
  - echo "Before Script"
  - sudo service slapd stop
  - sleep 3
  - ls -la
  - sudo service slapd start
  - sudo rm /etc/ldap/slapd.d/* -R
  - sudo rm /var/lib/ldap/* -R
  - sudo cp ./ldap-test-database/slapd.d/* /etc/ldap/slapd.d/ -R
  - sudo chown openldap:openldap /etc/ldap/slapd.d/ -R
  - sudo cp ./ldap-test-database/ldap/* /var/lib/ldap/ -R
  - sudo chown openldap:openldap /var/lib/ldap/ -R
  - sudo service slapd start
  - composer install --no-interaction
  
