language: php
sudo: required
addons:
  apt:
    packages:
    - ldap-utils
    - slapd
    - php5-ldap
before_script:
  - echo "Before Script"
  - sudo service slapd stop
  - sleep 3
  - ls -la
  - sudo rm /etc/ldap/slapd.d/* -R
  - sudo slapadd -n 0 -F /etc/ldap/slapd.d -l ./ldap-test-database/config.ldif
  - sudo slapadd -n 1 -l ./ldap-test-database/data.ldif
  - sudo chown openldap:openldap /etc/ldap/slapd.d/ -R
  - sudo chown openldap:openldap /var/lib/ldap/ -R
  - sudo service slapd start
  - composer install --no-interaction
  
