# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    ldap.frontend:
        class: AppBundle\model\ldapCon\LDAPService
        arguments: ["@logger","@session"]
    login:
        class: AppBundle\model\login\LoginHandler
        arguments: ['@ldap.frontend']
    login.User:
            class: AppBundle\model\login\loggedInUserService
            arguments: ['@ldap.frontend']
    organisation:
        class: AppBundle\model\usersLDAP\Organisation
        arguments: ['@ldap.frontend',"@logger","@session"]
