# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    ldap.frontend:
        class: AppBundle\model\ldapCon\LDAPService
        arguments: ["@logger","@session"]
    organisation:
        class: AppBundle\model\usersLDAP\Organisation
        arguments: ['@ldap.frontend',"@logger","@session"]
    your.monolog.service.id:
        class: Monolog\Formatter\LineFormatter
        calls:
            - [includeStacktraces]
    ldap_user_provider:
            class: AppBundle\Security\LDAPUserProvider
            arguments: ['@ldap.frontend',"@logger","@session","@organisation"]
    ssha_encoder:
        class: AppBundle\Security\MessageDigestPasswordEncoder