version: 2
jobs:
    build:
        docker:
            - image: buildpack-deps:xenial
        environment:
            TZ: "/usr/share/zoneinfo/America/Los_Angeles"
            DEBIAN_FRONTEND: "noninteractive"
        working_directory: /var/www/html
        steps:
            - run: apt-get update && apt-get -y install git unzip zlib1g-dev sudo php php7.0-mbstring php7.0-zip php7.0-xml
            - checkout
            - run:
                name: Install LDAP
                command: |
                    sudo DEBIAN_FRONTEND=noninteractive apt-get -yq --no-install-suggests --no-install-recommends --force-yes install ldap-utils slapd php7.0-ldap ; \
                    sudo service slapd stop ; \
                    sudo rm /etc/ldap/slapd.d/* -R ; \
                    sudo slapadd -n 0 -F /etc/ldap/slapd.d -l ./ldap-test-database/config.ldif ; \
                    sudo slapadd -n 1 -l ./ldap-test-database/data.ldif ; \
                    sudo chown openldap:openldap /etc/ldap/slapd.d/ -R ; \
                    sudo chown openldap:openldap /var/lib/ldap/ -R ; \
                    sudo service slapd start
            - run: php composer.phar install --no-interaction
            - run: ./vendor/bin/phpunit
