version: 2
jobs:
    build:
        working_directory: /var/www/html
        steps:
            - run: apt-get update && apt-get -y install git unzip zlib1g-dev
            - checkout
            - run:
                name: Install LDAP
                command: |
                    export DEBIAN_FRONTEND=noninteractive && \
                    sudo apt-get -yq --no-install-suggests --no-install-recommends --force-yes install ldap-utils slapd php7.0-ldap
                    sudo service slapd stop && \
                    sudo rm /etc/ldap/slapd.d/* -R && \
                    sudo slapadd -n 0 -F /etc/ldap/slapd.d -l ./ldap-test-database/config.ldif && \
                    sudo slapadd -n 1 -l ./ldap-test-database/data.ldif && \
                    sudo chown openldap:openldap /etc/ldap/slapd.d/ -R && \
                    sudo chown openldap:openldap /var/lib/ldap/ -R && \
                    sudo service slapd start
             - run: vendor/bin/phpunit
